import { useState } from 'react';
import { Bell, CalendarDays, Check, Clock3, Flag, LoaderCircle, Pencil, Repeat2, Trash2 } from 'lucide-react';
import { dateKey, dayLabel, timeText } from '../lib/dates';
import { recurrenceLabel } from '../lib/recurrenceLabel';
import { api, errorMessage } from '../lib/api';
import type { CalendarEvent, Task, TaskOccurrence } from '../lib/types';
import { Modal } from './ui';

export function EventDetails({ event, timezone, onClose, onEdit, onDeleted }: { event: CalendarEvent; timezone: string; onClose: () => void; onEdit: (event: CalendarEvent) => void; onDeleted: () => void }) {
  const [deleting, setDeleting] = useState(false), [scope, setScope] = useState<'all' | 'this' | 'future'>(event.occurrence_at ? 'this' : 'all'), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const displayTimezone = event.all_day ? event.timezone : timezone;
  const firstDay = dateKey(event.start_at, displayTimezone);
  const lastDay = dateKey(new Date(Date.parse(event.end_at) - 1), displayTimezone);
  const dateLabel = firstDay !== lastDay
    ? `${dayLabel(firstDay, { day: 'numeric', month: 'long', ...(firstDay.slice(0, 4) !== lastDay.slice(0, 4) ? { year: 'numeric' } : {}) })} — ${dayLabel(lastDay, { day: 'numeric', month: 'long', ...(firstDay.slice(0, 4) !== lastDay.slice(0, 4) ? { year: 'numeric' } : {}) })}`
    : dayLabel(firstDay, { weekday: 'long', day: 'numeric', month: 'long' });
  async function edit() { setBusy(true); try { const base = await api<CalendarEvent>(`/planning/events/${event.id}`); onEdit(base); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); } }
  return <Modal title={deleting ? 'Удалить событие?' : event.title} onClose={() => !busy && onClose()} className="detail-modal"><div className="modal-body">{deleting ? <><p>«{event.title}» будет удалено из календаря. Это действие нельзя отменить.</p>{event.recurrence && <fieldset className="scope-options"><legend>Какие события удалить?</legend>{([['this', 'Только это событие'], ['future', 'Это и все последующие'], ['all', 'Всю серию']] as const).map(([key, label]) => <label key={key}><input type="radio" name="scope" value={key} checked={scope === key} disabled={key !== 'all' && !event.occurrence_at} onChange={() => setScope(key)} />{label}</label>)}</fieldset>}</> : <><span className="badge"><CalendarDays size={13} />Событие</span><div className="detail-facts"><p><CalendarDays size={18} /><span>{dateLabel}</span></p><p><Clock3 size={18} /><span>{event.all_day ? 'Весь день' : `${timeText(event.start_at, timezone)} — ${timeText(event.end_at, timezone)}`}<small>{displayTimezone.replaceAll('_', ' ')}</small></span></p>{event.recurrence && <p><Repeat2 size={18} /><span>{recurrenceLabel(event.recurrence.rrule, event.recurrence.timezone)}</span></p>}</div>{event.notes && <div className="detail-notes">{event.notes}</div>}{event.external_read_only && <p className="notice">Только для чтения. Изменения доступны в исходном календаре.</p>}</>}{error && <p className="field-error" role="alert">{error}</p>}</div><footer className="modal-footer">{deleting ? <><button className="button secondary" disabled={busy} onClick={() => setDeleting(false)}>Отмена</button><button className="button danger" disabled={busy} onClick={async () => { setBusy(true); try { const query = new URLSearchParams({ scope, version: String(event.version) }); if (event.occurrence_at && scope !== 'all') query.set('occurrence_at', event.occurrence_at); await api(`/planning/events/${event.id}?${query}`, { method: 'DELETE' }); onDeleted(); onClose(); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); } }}>{busy ? <LoaderCircle size={15} className="spinner" /> : <Trash2 size={15} />}Удалить</button></> : event.external_read_only ? <button className="button secondary" onClick={onClose}>Закрыть</button> : <><button className="button ghost danger-text" disabled={busy} onClick={() => setDeleting(true)}><Trash2 size={16} />Удалить</button><button className="button primary" disabled={busy} onClick={() => void edit()}>{busy ? <LoaderCircle size={15} className="spinner" /> : <Pencil size={15} />}Редактировать</button></>}</footer></Modal>;
}

export function TaskDetails({ task, occurrence, timezone, busy, onClose, onToggle, onEdit }: { task: Task; occurrence?: TaskOccurrence; timezone: string; busy: boolean; onClose: () => void; onToggle: () => void; onEdit: () => void }) {
  const at = occurrence?.effective_due_at || occurrence?.effective_start_at || task.due_at || task.start_at;
  const displayTimezone = task.all_day ? task.timezone : timezone;
  const complete = occurrence ? occurrence.status === 'completed' : task.completed;
  return <Modal title={task.title} onClose={onClose} className="detail-modal"><div className="modal-body"><span className="badge">Задача</span><div className="detail-facts">{at && <p><CalendarDays size={18} /><span>{dayLabel(dateKey(at, displayTimezone))}{!task.all_day && ` · ${timeText(at, timezone)}`}<small>{displayTimezone.replaceAll('_', ' ')}</small></span></p>}{task.priority !== 'none' && <p><Flag size={18} /><span>{{ high: 'Высокий', medium: 'Средний', low: 'Низкий' }[task.priority]} приоритет</span></p>}{task.recurrence && <p><Repeat2 size={18} /><span>{recurrenceLabel(task.recurrence.rrule, task.recurrence.timezone)}</span></p>}{task.reminders.length > 0 && <p><Bell size={18} /><span>Напоминаний: {task.reminders.length}</span></p>}</div>{task.notes && <div className="detail-notes">{task.notes}</div>}</div><footer className="modal-footer"><button className="button secondary" onClick={onEdit}><Pencil size={15} />Редактировать</button><button className="button primary" disabled={busy} onClick={onToggle}>{busy ? <LoaderCircle size={15} className="spinner" /> : <Check size={15} />}{complete ? 'Вернуть в задачи' : 'Выполнить'}</button></footer></Modal>;
}
