"""Initial authentication and planning schema

Revision ID: 0001
Revises:
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_attempts',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('failures', sa.Integer(), nullable=False),
    sa.Column('blocked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('email', name=op.f('pk_login_attempts'))
    )
    op.create_table('pending_registrations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('otp_hash', sa.String(length=64), nullable=False),
    sa.Column('otp_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('resend_count', sa.Integer(), nullable=False),
    sa.Column('last_sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pending_registrations')),
    sa.UniqueConstraint('email', name=op.f('uq_pending_registrations_email'))
    )
    op.create_index(op.f('ix_pending_registrations_expires_at'), 'pending_registrations', ['expires_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('plan', sa.String(length=10), nullable=False),
    sa.Column('trial_ends', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('free_modules', sa.JSON(), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index('uq_users_password_email', 'users', ['email'], unique=True, postgresql_where=sa.text('password_hash IS NOT NULL'), sqlite_where=sa.text('password_hash IS NOT NULL'))
    op.create_table('auth_identities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=12), nullable=False),
    sa.Column('provider_subject', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_auth_identities_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_identities')),
    sa.UniqueConstraint('provider', 'provider_subject', name='uq_identity_provider_subject')
    )
    op.create_index(op.f('ix_auth_identities_user_id'), 'auth_identities', ['user_id'], unique=False)
    op.create_table('calendar_connections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('calendar_id', sa.String(length=1024), nullable=False),
    sa.Column('account_label', sa.String(length=320), nullable=False),
    sa.Column('encrypted_credentials', sa.Text(), nullable=True),
    sa.Column('device_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('sync_enabled', sa.Boolean(), nullable=False),
    sa.Column('active_job_id', sa.Uuid(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_sync_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_calendar_connections_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calendar_connections')),
    sa.UniqueConstraint('user_id', 'provider', name='uq_calendar_user_provider')
    )
    op.create_index(op.f('ix_calendar_connections_next_sync_at'), 'calendar_connections', ['next_sync_at'], unique=False)
    op.create_index(op.f('ix_calendar_connections_user_id'), 'calendar_connections', ['user_id'], unique=False)
    op.create_table('calendar_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('all_day', sa.Boolean(), nullable=False),
    sa.Column('rrule', sa.String(length=2000), nullable=True),
    sa.Column('source', sa.String(length=12), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=True),
    sa.Column('external_read_only', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('end_at > start_at', name=op.f('ck_calendar_events_ck_event_positive_duration')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_calendar_events_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calendar_events'))
    )
    op.create_index(op.f('ix_calendar_events_connection_id'), 'calendar_events', ['connection_id'], unique=False)
    op.create_index(op.f('ix_calendar_events_deleted_at'), 'calendar_events', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_calendar_events_end_at'), 'calendar_events', ['end_at'], unique=False)
    op.create_index(op.f('ix_calendar_events_start_at'), 'calendar_events', ['start_at'], unique=False)
    op.create_index(op.f('ix_calendar_events_user_id'), 'calendar_events', ['user_id'], unique=False)
    op.create_table('calendar_oauth_states',
    sa.Column('state_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('redirect_uri', sa.String(length=2048), nullable=False),
    sa.Column('device_id', sa.String(length=128), nullable=True),
    sa.Column('encrypted_verifier', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_calendar_oauth_states_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('state_hash', name=op.f('pk_calendar_oauth_states'))
    )
    op.create_index(op.f('ix_calendar_oauth_states_user_id'), 'calendar_oauth_states', ['user_id'], unique=False)
    op.create_table('email_change_challenges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('new_email', sa.String(length=320), nullable=False),
    sa.Column('otp_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('registration_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('resend_count', sa.Integer(), nullable=False),
    sa.Column('last_sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_email_change_challenges_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_change_challenges')),
    sa.UniqueConstraint('user_id', name=op.f('uq_email_change_challenges_user_id'))
    )
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_password_reset_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_reset_tokens')),
    sa.UniqueConstraint('user_id', name=op.f('uq_password_reset_tokens_user_id'))
    )
    op.create_table('planning_ai_usage',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_planning_ai_usage_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'day', name=op.f('pk_planning_ai_usage'))
    )
    op.create_table('planning_commands',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('response', sa.JSON(), nullable=True),
    sa.Column('error_status', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_planning_commands_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_planning_commands')),
    sa.UniqueConstraint('user_id', 'idempotency_key', name=op.f('uq_planning_commands_user_id'))
    )
    op.create_index(op.f('ix_planning_commands_user_id'), 'planning_commands', ['user_id'], unique=False)
    op.create_table('planning_lists',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('system_key', sa.String(length=20), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_planning_lists_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_planning_lists')),
    sa.UniqueConstraint('user_id', 'system_key', name='uq_planning_system_list')
    )
    op.create_index(op.f('ix_planning_lists_user_id'), 'planning_lists', ['user_id'], unique=False)
    op.create_table('planning_reminders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=10), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('trigger_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('offset_minutes', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=10), nullable=False),
    sa.Column('next_trigger_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('occurrence_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_key', sa.String(length=100), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(length=100), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_token', sa.Uuid(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_planning_reminders_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_planning_reminders'))
    )
    op.create_index(op.f('ix_planning_reminders_entity_id'), 'planning_reminders', ['entity_id'], unique=False)
    op.create_index(op.f('ix_planning_reminders_next_trigger_at'), 'planning_reminders', ['next_trigger_at'], unique=False)
    op.create_index(op.f('ix_planning_reminders_user_id'), 'planning_reminders', ['user_id'], unique=False)
    op.create_index('ix_reminder_due', 'planning_reminders', ['next_trigger_at', 'cancelled_at'], unique=False)
    op.create_table('refresh_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_id', sa.Uuid(), nullable=True),
    sa.Column('device_info', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_sessions_token_hash'))
    )
    op.create_index(op.f('ix_refresh_sessions_expires_at'), 'refresh_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_sessions_family_id'), 'refresh_sessions', ['family_id'], unique=False)
    op.create_index(op.f('ix_refresh_sessions_user_id'), 'refresh_sessions', ['user_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('all_day', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('rrule', sa.String(length=2000), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("priority IN ('none','low','medium','high')", name=op.f('ck_tasks_ck_task_priority')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tasks_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    op.create_index(op.f('ix_tasks_deleted_at'), 'tasks', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_tasks_due_at'), 'tasks', ['due_at'], unique=False)
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.create_table('calendar_sync_cursors',
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('cursor', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['calendar_connections.id'], name=op.f('fk_calendar_sync_cursors_connection_id_calendar_connections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('connection_id', name=op.f('pk_calendar_sync_cursors'))
    )
    op.create_table('calendar_sync_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('phase', sa.String(length=24), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('push_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_owner', sa.String(length=64), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['calendar_connections.id'], name=op.f('fk_calendar_sync_jobs_connection_id_calendar_connections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calendar_sync_jobs'))
    )
    op.create_index('ix_calendar_jobs_due', 'calendar_sync_jobs', ['status', 'available_at'], unique=False)
    op.create_index(op.f('ix_calendar_sync_jobs_connection_id'), 'calendar_sync_jobs', ['connection_id'], unique=False)
    op.create_table('event_exceptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('occurrence_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['calendar_events.id'], name=op.f('fk_event_exceptions_event_id_calendar_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_event_exceptions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_exceptions')),
    sa.UniqueConstraint('event_id', 'occurrence_at', name='uq_event_exception')
    )
    op.create_index(op.f('ix_event_exceptions_event_id'), 'event_exceptions', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_exceptions_user_id'), 'event_exceptions', ['user_id'], unique=False)
    op.create_table('external_event_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=1024), nullable=False),
    sa.Column('etag', sa.String(length=512), nullable=True),
    sa.Column('synced_version', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=True),
    sa.Column('remote_exists', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['calendar_connections.id'], name=op.f('fk_external_event_links_connection_id_calendar_connections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['calendar_events.id'], name=op.f('fk_external_event_links_event_id_calendar_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_external_event_links')),
    sa.UniqueConstraint('connection_id', 'event_id', name='uq_calendar_local_event'),
    sa.UniqueConstraint('connection_id', 'external_id', name='uq_calendar_external_event')
    )
    op.create_index(op.f('ix_external_event_links_connection_id'), 'external_event_links', ['connection_id'], unique=False)
    op.create_index(op.f('ix_external_event_links_event_id'), 'external_event_links', ['event_id'], unique=False)
    op.create_table('list_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('list_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('checked', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['list_id'], ['planning_lists.id'], name=op.f('fk_list_items_list_id_planning_lists'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_list_items_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_list_items'))
    )
    op.create_index(op.f('ix_list_items_list_id'), 'list_items', ['list_id'], unique=False)
    op.create_index(op.f('ix_list_items_user_id'), 'list_items', ['user_id'], unique=False)
    op.create_table('task_occurrences',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('occurrence_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_task_occurrences_task_id_tasks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_task_occurrences_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_occurrences')),
    sa.UniqueConstraint('task_id', 'occurrence_at', name='uq_task_occurrence')
    )
    op.create_index(op.f('ix_task_occurrences_task_id'), 'task_occurrences', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_occurrences_user_id'), 'task_occurrences', ['user_id'], unique=False)
    op.create_table('apple_inbound_batches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('cursor', sa.Text(), nullable=True),
    sa.Column('final', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['calendar_connections.id'], name=op.f('fk_apple_inbound_batches_connection_id_calendar_connections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['calendar_sync_jobs.id'], name=op.f('fk_apple_inbound_batches_job_id_calendar_sync_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_apple_inbound_batches')),
    sa.UniqueConstraint('connection_id', 'batch_id', name='uq_apple_inbound_batch')
    )
    op.create_index(op.f('ix_apple_inbound_batches_connection_id'), 'apple_inbound_batches', ['connection_id'], unique=False)
    op.create_index(op.f('ix_apple_inbound_batches_job_id'), 'apple_inbound_batches', ['job_id'], unique=False)
    op.create_table('apple_outbound_changes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('event_version', sa.Integer(), nullable=False),
    sa.Column('operation', sa.String(length=16), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('external_id', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['calendar_connections.id'], name=op.f('fk_apple_outbound_changes_connection_id_calendar_connections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['calendar_events.id'], name=op.f('fk_apple_outbound_changes_event_id_calendar_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['calendar_sync_jobs.id'], name=op.f('fk_apple_outbound_changes_job_id_calendar_sync_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_apple_outbound_changes')),
    sa.UniqueConstraint('connection_id', 'event_id', 'event_version', name='uq_apple_outbound_version')
    )
    op.create_index(op.f('ix_apple_outbound_changes_connection_id'), 'apple_outbound_changes', ['connection_id'], unique=False)
    op.create_index(op.f('ix_apple_outbound_changes_job_id'), 'apple_outbound_changes', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_apple_outbound_changes_job_id'), table_name='apple_outbound_changes')
    op.drop_index(op.f('ix_apple_outbound_changes_connection_id'), table_name='apple_outbound_changes')
    op.drop_table('apple_outbound_changes')
    op.drop_index(op.f('ix_apple_inbound_batches_job_id'), table_name='apple_inbound_batches')
    op.drop_index(op.f('ix_apple_inbound_batches_connection_id'), table_name='apple_inbound_batches')
    op.drop_table('apple_inbound_batches')
    op.drop_index(op.f('ix_task_occurrences_user_id'), table_name='task_occurrences')
    op.drop_index(op.f('ix_task_occurrences_task_id'), table_name='task_occurrences')
    op.drop_table('task_occurrences')
    op.drop_index(op.f('ix_list_items_user_id'), table_name='list_items')
    op.drop_index(op.f('ix_list_items_list_id'), table_name='list_items')
    op.drop_table('list_items')
    op.drop_index(op.f('ix_external_event_links_event_id'), table_name='external_event_links')
    op.drop_index(op.f('ix_external_event_links_connection_id'), table_name='external_event_links')
    op.drop_table('external_event_links')
    op.drop_index(op.f('ix_event_exceptions_user_id'), table_name='event_exceptions')
    op.drop_index(op.f('ix_event_exceptions_event_id'), table_name='event_exceptions')
    op.drop_table('event_exceptions')
    op.drop_index(op.f('ix_calendar_sync_jobs_connection_id'), table_name='calendar_sync_jobs')
    op.drop_index('ix_calendar_jobs_due', table_name='calendar_sync_jobs')
    op.drop_table('calendar_sync_jobs')
    op.drop_table('calendar_sync_cursors')
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_due_at'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_deleted_at'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_refresh_sessions_user_id'), table_name='refresh_sessions')
    op.drop_index(op.f('ix_refresh_sessions_family_id'), table_name='refresh_sessions')
    op.drop_index(op.f('ix_refresh_sessions_expires_at'), table_name='refresh_sessions')
    op.drop_table('refresh_sessions')
    op.drop_index('ix_reminder_due', table_name='planning_reminders')
    op.drop_index(op.f('ix_planning_reminders_user_id'), table_name='planning_reminders')
    op.drop_index(op.f('ix_planning_reminders_next_trigger_at'), table_name='planning_reminders')
    op.drop_index(op.f('ix_planning_reminders_entity_id'), table_name='planning_reminders')
    op.drop_table('planning_reminders')
    op.drop_index(op.f('ix_planning_lists_user_id'), table_name='planning_lists')
    op.drop_table('planning_lists')
    op.drop_index(op.f('ix_planning_commands_user_id'), table_name='planning_commands')
    op.drop_table('planning_commands')
    op.drop_table('planning_ai_usage')
    op.drop_table('password_reset_tokens')
    op.drop_table('email_change_challenges')
    op.drop_index(op.f('ix_calendar_oauth_states_user_id'), table_name='calendar_oauth_states')
    op.drop_table('calendar_oauth_states')
    op.drop_index(op.f('ix_calendar_events_user_id'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_start_at'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_end_at'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_deleted_at'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_connection_id'), table_name='calendar_events')
    op.drop_table('calendar_events')
    op.drop_index(op.f('ix_calendar_connections_user_id'), table_name='calendar_connections')
    op.drop_index(op.f('ix_calendar_connections_next_sync_at'), table_name='calendar_connections')
    op.drop_table('calendar_connections')
    op.drop_index(op.f('ix_auth_identities_user_id'), table_name='auth_identities')
    op.drop_table('auth_identities')
    op.drop_index('uq_users_password_email', table_name='users', postgresql_where=sa.text('password_hash IS NOT NULL'), sqlite_where=sa.text('password_hash IS NOT NULL'))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_pending_registrations_expires_at'), table_name='pending_registrations')
    op.drop_table('pending_registrations')
    op.drop_table('login_attempts')
    # ### end Alembic commands ###
