"""Goals, habits, health, finance, books and diary."""

from alembic import op
import sqlalchemy as sa

revision = "0003_product_modules"
down_revision = "0002_web_push"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "books",
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("author", sa.String(length=300), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("total_pages", sa.Integer(), nullable=True),
        sa.Column("current_page", sa.Integer(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.Column("genre", sa.String(length=100), nullable=False),
        sa.Column("cover_id", sa.Integer(), nullable=True),
        sa.Column("open_library_key", sa.String(length=60), nullable=True),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("started_on", sa.Date(), nullable=True),
        sa.Column("finished_on", sa.Date(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_books_user_id_users"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_books")),
    )
    op.create_index(op.f("ix_books_deleted_at"), "books", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_books_user_id"), "books", ["user_id"], unique=False)
    op.create_table(
        "diary_entries",
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_diary_entries_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_diary_entries")),
    )
    op.create_index(op.f("ix_diary_entries_day"), "diary_entries", ["day"], unique=False)
    op.create_index(op.f("ix_diary_entries_deleted_at"), "diary_entries", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_diary_entries_user_id"), "diary_entries", ["user_id"], unique=False)
    op.create_table(
        "finance_budgets",
        sa.Column("month", sa.String(length=7), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("amount", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_finance_budgets_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_finance_budgets")),
    )
    op.create_index(op.f("ix_finance_budgets_deleted_at"), "finance_budgets", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_finance_budgets_month"), "finance_budgets", ["month"], unique=False)
    op.create_index(op.f("ix_finance_budgets_user_id"), "finance_budgets", ["user_id"], unique=False)
    op.create_table(
        "finance_debts",
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("direction", sa.String(length=12), nullable=False),
        sa.Column("amount", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_finance_debts_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_finance_debts")),
    )
    op.create_index(op.f("ix_finance_debts_deleted_at"), "finance_debts", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_finance_debts_user_id"), "finance_debts", ["user_id"], unique=False)
    op.create_table(
        "finance_goals",
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("target", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("saved", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_finance_goals_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_finance_goals")),
    )
    op.create_index(op.f("ix_finance_goals_deleted_at"), "finance_goals", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_finance_goals_user_id"), "finance_goals", ["user_id"], unique=False)
    op.create_table(
        "finance_savings",
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("amount", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_finance_savings_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_finance_savings")),
    )
    op.create_index(op.f("ix_finance_savings_deleted_at"), "finance_savings", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_finance_savings_user_id"), "finance_savings", ["user_id"], unique=False)
    op.create_table(
        "finance_subscriptions",
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("amount", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("period", sa.String(length=12), nullable=False),
        sa.Column("next_payment", sa.Date(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_finance_subscriptions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_finance_subscriptions")),
    )
    op.create_index(op.f("ix_finance_subscriptions_deleted_at"), "finance_subscriptions", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_finance_subscriptions_user_id"), "finance_subscriptions", ["user_id"], unique=False)
    op.create_table(
        "finance_transactions",
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("kind", sa.String(length=8), nullable=False),
        sa.Column("amount", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_finance_transactions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_finance_transactions")),
    )
    op.create_index(op.f("ix_finance_transactions_day"), "finance_transactions", ["day"], unique=False)
    op.create_index(op.f("ix_finance_transactions_deleted_at"), "finance_transactions", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_finance_transactions_user_id"), "finance_transactions", ["user_id"], unique=False)
    op.create_table(
        "goals",
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_goals_user_id_users"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_goals")),
    )
    op.create_index(op.f("ix_goals_deleted_at"), "goals", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_goals_user_id"), "goals", ["user_id"], unique=False)
    op.create_table(
        "health_medications",
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("dosage", sa.String(length=100), nullable=False),
        sa.Column("times", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_health_medications_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_health_medications")),
    )
    op.create_index(op.f("ix_health_medications_deleted_at"), "health_medications", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_health_medications_user_id"), "health_medications", ["user_id"], unique=False)
    op.create_table(
        "health_nutrition",
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("meal", sa.String(length=12), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("calories", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("protein", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("fat", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("carbs", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_health_nutrition_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_health_nutrition")),
    )
    op.create_index(op.f("ix_health_nutrition_day"), "health_nutrition", ["day"], unique=False)
    op.create_index(op.f("ix_health_nutrition_deleted_at"), "health_nutrition", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_health_nutrition_user_id"), "health_nutrition", ["user_id"], unique=False)
    op.create_table(
        "health_sleep",
        sa.Column("start_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("quality", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_health_sleep_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_health_sleep")),
    )
    op.create_index(op.f("ix_health_sleep_deleted_at"), "health_sleep", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_health_sleep_end_at"), "health_sleep", ["end_at"], unique=False)
    op.create_index(op.f("ix_health_sleep_user_id"), "health_sleep", ["user_id"], unique=False)
    op.create_table(
        "health_weight",
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("kg", sa.Numeric(precision=7, scale=3), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_health_weight_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_health_weight")),
    )
    op.create_index(op.f("ix_health_weight_day"), "health_weight", ["day"], unique=False)
    op.create_index(op.f("ix_health_weight_deleted_at"), "health_weight", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_health_weight_user_id"), "health_weight", ["user_id"], unique=False)
    op.create_table(
        "health_workouts",
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("minutes", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_health_workouts_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_health_workouts")),
    )
    op.create_index(op.f("ix_health_workouts_day"), "health_workouts", ["day"], unique=False)
    op.create_index(op.f("ix_health_workouts_deleted_at"), "health_workouts", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_health_workouts_user_id"), "health_workouts", ["user_id"], unique=False)
    op.create_table(
        "finance_debt_payments",
        sa.Column("debt_id", sa.Uuid(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["debt_id"],
            ["finance_debts.id"],
            name=op.f("fk_finance_debt_payments_debt_id_finance_debts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_finance_debt_payments_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_finance_debt_payments")),
    )
    op.create_index(op.f("ix_finance_debt_payments_debt_id"), "finance_debt_payments", ["debt_id"], unique=False)
    op.create_index(op.f("ix_finance_debt_payments_deleted_at"), "finance_debt_payments", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_finance_debt_payments_user_id"), "finance_debt_payments", ["user_id"], unique=False)
    op.create_table(
        "goal_milestones",
        sa.Column("goal_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["goal_id"], ["goals.id"], name=op.f("fk_goal_milestones_goal_id_goals"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_goal_milestones_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_goal_milestones")),
    )
    op.create_index(op.f("ix_goal_milestones_deleted_at"), "goal_milestones", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_goal_milestones_goal_id"), "goal_milestones", ["goal_id"], unique=False)
    op.create_index(op.f("ix_goal_milestones_user_id"), "goal_milestones", ["user_id"], unique=False)
    op.create_table(
        "goal_task_links",
        sa.Column("goal_id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["goal_id"], ["goals.id"], name=op.f("fk_goal_task_links_goal_id_goals"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_goal_task_links_task_id_tasks"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("goal_id", "task_id", name=op.f("pk_goal_task_links")),
    )
    op.create_table(
        "habits",
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("target", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("unit", sa.String(length=40), nullable=False),
        sa.Column("weekdays", sa.JSON(), nullable=False),
        sa.Column("reminder_time", sa.String(length=5), nullable=True),
        sa.Column("goal_id", sa.Uuid(), nullable=True),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["goal_id"], ["goals.id"], name=op.f("fk_habits_goal_id_goals"), ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_habits_user_id_users"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_habits")),
    )
    op.create_index(op.f("ix_habits_deleted_at"), "habits", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_habits_goal_id"), "habits", ["goal_id"], unique=False)
    op.create_index(op.f("ix_habits_user_id"), "habits", ["user_id"], unique=False)
    op.create_table(
        "health_medication_intakes",
        sa.Column("medication_id", sa.Uuid(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("time", sa.String(length=5), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["medication_id"],
            ["health_medications.id"],
            name=op.f("fk_health_medication_intakes_medication_id_health_medications"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_health_medication_intakes_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_health_medication_intakes")),
        sa.UniqueConstraint("medication_id", "day", "time", name="uq_medication_intake_slot"),
    )
    op.create_index(op.f("ix_health_medication_intakes_day"), "health_medication_intakes", ["day"], unique=False)
    op.create_index(
        op.f("ix_health_medication_intakes_deleted_at"), "health_medication_intakes", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_health_medication_intakes_medication_id"), "health_medication_intakes", ["medication_id"], unique=False
    )
    op.create_index(
        op.f("ix_health_medication_intakes_user_id"), "health_medication_intakes", ["user_id"], unique=False
    )
    op.create_table(
        "habit_checkins",
        sa.Column("habit_id", sa.Uuid(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("value", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["habit_id"], ["habits.id"], name=op.f("fk_habit_checkins_habit_id_habits"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_habit_checkins_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_habit_checkins")),
        sa.UniqueConstraint("habit_id", "day", name="uq_habit_checkin_day"),
    )
    op.create_index(op.f("ix_habit_checkins_day"), "habit_checkins", ["day"], unique=False)
    op.create_index(op.f("ix_habit_checkins_deleted_at"), "habit_checkins", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_habit_checkins_habit_id"), "habit_checkins", ["habit_id"], unique=False)
    op.create_index(op.f("ix_habit_checkins_user_id"), "habit_checkins", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("habit_checkins")
    op.drop_table("health_medication_intakes")
    op.drop_table("habits")
    op.drop_table("goal_task_links")
    op.drop_table("goal_milestones")
    op.drop_table("finance_debt_payments")
    op.drop_table("health_workouts")
    op.drop_table("health_weight")
    op.drop_table("health_sleep")
    op.drop_table("health_nutrition")
    op.drop_table("health_medications")
    op.drop_table("goals")
    op.drop_table("finance_transactions")
    op.drop_table("finance_subscriptions")
    op.drop_table("finance_savings")
    op.drop_table("finance_goals")
    op.drop_table("finance_debts")
    op.drop_table("finance_budgets")
    op.drop_table("diary_entries")
    op.drop_table("books")
    # ### end Alembic commands ###
