"""Deduplicated product reminder delivery."""

from alembic import op
import sqlalchemy as sa

revision = "0005_product_notices"
down_revision = "0004_user_privacy"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_notices",
        sa.Column("key", sa.String(length=160), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("module", sa.String(length=32), nullable=False),
        sa.Column("pro_only", sa.Boolean(), nullable=False),
        sa.Column("url", sa.String(length=100), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retry_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_product_notices_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_product_notices")),
    )
    op.create_index(op.f("ix_product_notices_expires_at"), "product_notices", ["expires_at"], unique=False)
    op.create_index(op.f("ix_product_notices_retry_at"), "product_notices", ["retry_at"], unique=False)
    op.create_index(op.f("ix_product_notices_user_id"), "product_notices", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    op.drop_table("product_notices")
