"""Custom workout programs and private weight targets."""

from alembic import op
import sqlalchemy as sa

revision = "0006_health_programs"
down_revision = "0005_product_notices"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "health_programs",
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("exercises", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_health_programs_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_health_programs")),
    )
    op.create_index(op.f("ix_health_programs_user_id"), "health_programs", ["user_id"], unique=False)
    op.create_index(op.f("ix_health_programs_deleted_at"), "health_programs", ["deleted_at"], unique=False)
    op.create_table(
        "health_weight_targets",
        sa.Column("kg", sa.Numeric(precision=7, scale=3), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_health_weight_targets_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_health_weight_targets")),
    )
    op.create_index(op.f("ix_health_weight_targets_user_id"), "health_weight_targets", ["user_id"], unique=False)
    op.create_index(op.f("ix_health_weight_targets_deleted_at"), "health_weight_targets", ["deleted_at"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("health_weight_targets")
    op.drop_table("health_programs")
    # ### end Alembic commands ###
