"""Savings balance history."""

from alembic import op
import sqlalchemy as sa

revision = "0007_savings_history"
down_revision = "0006_health_programs"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "finance_savings_history",
        sa.Column("savings_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("previous_amount", sa.Numeric(precision=16, scale=2), nullable=True),
        sa.Column("previous_currency", sa.String(length=3), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["savings_id"],
            ["finance_savings.id"],
            name=op.f("fk_finance_savings_history_savings_id_finance_savings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_finance_savings_history_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_finance_savings_history")),
    )
    op.create_index(
        op.f("ix_finance_savings_history_deleted_at"), "finance_savings_history", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_finance_savings_history_savings_id"), "finance_savings_history", ["savings_id"], unique=False
    )
    op.create_index(op.f("ix_finance_savings_history_user_id"), "finance_savings_history", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    op.drop_table("finance_savings_history")
